const mmb_ge_mm3 = {
   capture_datetime: 'timestamp with time zone',
   system_id: 'text',
   host_date: 'text',
   host_time: 'text',
   host_datetime: 'timestamp with time zone',
   he_level_value: 'numeric',
   water_flow_value: 'numeric',
   water_temp_value: 'numeric',
   shield_si410_value: 'numeric',
   recon_ruo_value: 'numeric',
   recon_si410_value: 'numeric',
   coldhead_ruo_value: 'numeric',
   he_pressure_value: 'numeric',
   cdc1_value: 'numeric',
   cs1_value: 'numeric',
   ht_value: 'numeric',
   hdc_value: 'numeric',
   rf_value: 'numeric',
   fm_value: 'numeric',
   sm_value: 'numeric',
   ec1_value: 'numeric',
   ec2_value: 'numeric',
   ec3_value: 'numeric',
   ec4_value: 'numeric',
   water_flow_2_value: 'numeric',
   water_temp_2_value: 'numeric',
   cs2_value: 'numeric',
   cdc2_value: 'numeric',
   cmp1a_value: 'numeric',
   sc_pressure_value: 'numeric',
   alert_analysis_complete: 'boolean',
};

const mmb_ge_mm4 = {
   capture_datetime: 'timestamp with time zone',
   system_id: 'text',
   host_date: 'text',
   host_time: 'text',
   host_datetime: 'timestamp with time zone',
   he_level_value: 'numeric',
   water_flow_value: 'numeric',
   water_temp_value: 'numeric',
   shield_si410_value: 'numeric',
   recon_ruo_value: 'numeric',
   recon_si410_value: 'numeric',
   coldhead_ruo_value: 'numeric',
   he_pressure_value: 'numeric',
   case_temp_value: 'numeric',
   cdc1_value: 'numeric',
   alert_analysis_complete: 'boolean',
};

const mmb_siemens = {
   capture_datetime: 'timestamp with time zone',
   system_id: 'text',
   msup_metadata: 'text',
   or_dash_code: 'text',
   or_code: 'text',
   field_current_value: 'numeric',
   host_time: 'text',
   host_date: 'text',
   host_datetime: 'timestamp with time zone',
   sup_time: 'text',
   test_time: 'text',
   lvqd: 'text',
   msup_sn: 'text',
   msup_rev: 'text',
   magnet_sn: 'text',
   magnet_rev: 'text',
   he_params: 'text',
   he_param_1: 'text',
   he_param_2: 'text',
   he_alarm_low_value: 'numeric',
   he_alarm_high_value: 'numeric',
   he_warn_low_value: 'numeric',
   he_warn_high_value: 'numeric',
   he_level_1_value: 'numeric',
   he_level_2_value: 'numeric',
   he_status: 'text',
   eis_status: 'text',
   field: 'text',
   self_test_result: 'text',
   battery_status: 'text',
   sh_status: 'text',
   battery_volts_value: 'numeric',
   press_htr_status: 'text',
   press_htr_value: 'numeric',
   compressor_status: 'text',
   compressor_value: 'numeric',
   press_sw_status: 'text',
   cold_head_sensor_1_value: 'numeric',
   cold_head_status: 'text',
   shield_link_value: 'numeric',
   shield_bore_value: 'numeric',
   shield_sensor_1_value: 'numeric',
   shield_sensor_2_value: 'numeric',
   shield_status: 'text',
   turret_sensor_1_value: 'numeric',
   turret_sensor_2_value: 'numeric',
   turret_status: 'text',
   ccr_sensor_1_value: 'numeric',
   ccr_sensor_2_value: 'numeric',
   ccr_1_2_status: 'text',
   ccr_sensor_3_value: 'numeric',
   ccr_sensor_4_value: 'numeric',
   ccr_3_4_status: 'text',
   carbon_r_sensor_1_value: 'numeric',
   carbon_r_sensor_2_value: 'numeric',
   carbon_r_1_2_status: 'text',
   carbon_r_sensor_3_value: 'numeric',
   carbon_r_sensor_4_value: 'numeric',
   carbon_r_3_4_status: 'text',
   swt_htr_res_1_value: 'numeric',
   swt_htr_res_1_status: 'text',
   quh_htr_res_1_value: 'numeric',
   quh_htr_res_2_value: 'numeric',
   quh_htr_status: 'text',
   mag_psia_value: 'numeric',
   mag_psia_status: 'text',
   avg_power_value: 'numeric',
   avg_power_status: 'text',
   epm_status: 'text',
   erdu_status: 'text',
   erdu_buttons_value: 'numeric',
   erdu_1_status: 'text',
   erdu_2_status: 'text',
   erdu_3_status: 'text',
   tests: 'text',
   ibutton_sn: 'text',
   alert_analysis_complete: 'boolean',
};

const mmb_siemens_non_tim = {
   capture_datetime: 'timestamp with time zone',
   system_id: 'text',
   msup_metadata: 'text',
   host_time: 'text',
   host_date: 'text',
   host_datetime: 'timestamp with time zone',
   rx: 'text',
   tx: 'text',
   he_params: 'text',
   he_param_1: 'text',
   he_param_2: 'text',
   he_alarm_low_value: 'numeric',
   he_alarm_high_value: 'numeric',
   he_warn_low_value: 'numeric',
   he_warn_high_value: 'numeric',
   he_level_1_value: 'numeric',
   out_measure_status: 'text',
   sys_in_msg_sys_status: 'text',
   sys_pwr_fail: 'text',
   bat_out_erdu_bat_status: 'text',
   shield_out_fridge_status: 'text',
   shield_temp_value: 'numeric',
   shield_fridge_alarm_value: 'numeric',
   shield_fridge_warn_value: 'numeric',
   scru_out_eis_status: 'text',
   scru_in_msg_eis_status: 'text',
   emg_rd_in_msg_htr_status: 'text',
   in_msg_switch_status: 'text',
   cca_cab_out_air_con_status: 'text',
   cca_cab_temp_value: 'numeric',
   cca_cab_temp_alarm_value: 'numeric',
   cca_cab_temp_warn_value: 'numeric',
   gpa_cab_temp_value: 'numeric',
   gpa_cab_temp_alarm_value: 'numeric',
   gpa_cab_temp_warn_value: 'numeric',
   tests_in_mgs_fridge_status: 'text',
   tests_in_mgs_alarm_status: 'text',
   tests_in_erdu_load_status: 'text',
   shim_1_amps_value: 'numeric',
   shim_1_volts_value: 'numeric',
   shim_1_power_value: 'numeric',
   shim_1_status: 'text',
   shim_2_amps_value: 'numeric',
   shim_2_volts_value: 'numeric',
   shim_2_power_value: 'numeric',
   shim_2_status: 'text',
   shim_3_amps_value: 'numeric',
   shim_3_volts_value: 'numeric',
   shim_3_power_value: 'numeric',
   shim_3_status: 'text',
   shim_4_amps_value: 'numeric',
   shim_4_volts_value: 'numeric',
   shim_4_power_value: 'numeric',
   shim_4_status: 'text',
   shim_5_amps_value: 'numeric',
   shim_5_volts_value: 'numeric',
   shim_5_power_value: 'numeric',
   shim_5_status: 'text',
   dc_value: 'numeric',
   watts_value: 'numeric',
   alert_analysis_complete: 'boolean',
};

const mmb_edu2 = {
   capture_datetime: 'timestamp with time zone',
   system_id: 'text',
   temp_probe_0_value: 'numeric',
   temp_probe_1_value: 'numeric',
   room_humidity_value: 'numeric',
   room_temp_value: 'numeric',
   comp_vib_status: 'boolean',
   alert_analysis_complete: 'boolean',
};

module.exports = {
   mmb_ge_mm3,
   mmb_ge_mm4,
   mmb_siemens,
   mmb_siemens_non_tim,
   mmb_edu2,
};
